// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


var example_graph = /* record */[
  /* nodes : :: */[
    /* "b" */98,
    /* :: */[
      /* "c" */99,
      /* :: */[
        /* "d" */100,
        /* :: */[
          /* "f" */102,
          /* :: */[
            /* "g" */103,
            /* :: */[
              /* "h" */104,
              /* :: */[
                /* "k" */107,
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]
  ],
  /* edges : :: */[
    /* tuple */[
      /* "h" */104,
      /* "g" */103
    ],
    /* :: */[
      /* tuple */[
        /* "k" */107,
        /* "f" */102
      ],
      /* :: */[
        /* tuple */[
          /* "f" */102,
          /* "b" */98
        ],
        /* :: */[
          /* tuple */[
            /* "f" */102,
            /* "c" */99
          ],
          /* :: */[
            /* tuple */[
              /* "c" */99,
              /* "b" */98
            ],
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

exports.example_graph = example_graph;
/* No side effect */
