// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function last(_param) {
  while(true) {
    var param = _param;
    if (param) {
      var rest = param[1];
      if (rest) {
        _param = rest;
        continue ;
        
      } else {
        return /* Some */[param[0]];
      }
    } else {
      return /* None */0;
    }
  };
}

console.log(last(/* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ]
          ]
        ]));

console.log(/* None */0);

exports.last = last;
/*  Not a pure module */
