// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function last_two(_param) {
  while(true) {
    var param = _param;
    if (param) {
      var rest = param[1];
      if (rest) {
        if (rest[1]) {
          _param = rest;
          continue ;
          
        } else {
          return /* Some */[/* tuple */[
                    param[0],
                    rest[0]
                  ]];
        }
      } else {
        return /* None */0;
      }
    } else {
      return /* None */0;
    }
  };
}

console.log(last_two(/* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ]
          ]
        ]));

console.log(last_two(/* :: */[
          1,
          /* [] */0
        ]));

console.log(last_two(/* [] */0));

exports.last_two = last_two;
/*  Not a pure module */
