// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function at(_k, _l) {
  while(true) {
    var l = _l;
    var k = _k;
    if (l) {
      var match = +(k === 1);
      if (match !== 0) {
        return /* Some */[l[0]];
      } else {
        _l = l[1];
        _k = k - 1 | 0;
        continue ;
        
      }
    } else {
      return /* None */0;
    }
  };
}

console.log(at(2, /* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ]
          ]
        ]));

console.log(at(5, /* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ]
          ]
        ]));

console.log(/* None */0);

exports.at = at;
/*  Not a pure module */
