// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function length(param) {
  if (param) {
    return 1 + length(param[1]) | 0;
  } else {
    return 0;
  }
}

function length_tail(_$staropt$star, _l) {
  while(true) {
    var l = _l;
    var $staropt$star = _$staropt$star;
    var acc = $staropt$star ? $staropt$star[0] : 0;
    if (l) {
      _l = l[1];
      _$staropt$star = /* Some */[acc + 1 | 0];
      continue ;
      
    } else {
      return acc;
    }
  };
}

console.log(0);

console.log(length(/* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* [] */0
            ]
          ]
        ]));

console.log(length_tail(/* None */0, /* [] */0));

console.log(length_tail(/* None */0, /* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* [] */0
            ]
          ]
        ]));

exports.length      = length;
exports.length_tail = length_tail;
/*  Not a pure module */
