// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function rev(l) {
  var _l = l;
  var _acc = /* [] */0;
  while(true) {
    var acc = _acc;
    var l$1 = _l;
    if (l$1) {
      _acc = /* :: */[
        l$1[0],
        acc
      ];
      _l = l$1[1];
      continue ;
      
    } else {
      return acc;
    }
  };
}

console.log(rev(/* :: */[
          1,
          /* :: */[
            2,
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ]
          ]
        ]));

console.log(rev(/* :: */[
          1,
          /* [] */0
        ]));

console.log(rev(/* [] */0));

exports.rev = rev;
/*  Not a pure module */
