// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Block      = require("bs-platform/lib/js/block.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function flatten(param) {
  if (param) {
    return Pervasives.$at(aux(param[0]), flatten(param[1]));
  } else {
    return /* [] */0;
  }
}

function aux(param) {
  if (param.tag) {
    return flatten(param[0]);
  } else {
    return /* :: */[
            param[0],
            /* [] */0
          ];
  }
}

function flatten2(l) {
  var aux = function (_l, _acc) {
    while(true) {
      var acc = _acc;
      var l = _l;
      if (l) {
        var match = l[0];
        if (match.tag) {
          _acc = aux(match[0], acc);
          _l = l[1];
          continue ;
          
        } else {
          _acc = /* :: */[
            match[0],
            acc
          ];
          _l = l[1];
          continue ;
          
        }
      } else {
        return acc;
      }
    };
  };
  return List.rev(aux(l, /* [] */0));
}

console.log(flatten(/* :: */[
          /* One */Block.__(0, ["a"]),
          /* :: */[
            /* Many */Block.__(1, [/* :: */[
                  /* One */Block.__(0, ["b"]),
                  /* :: */[
                    /* Many */Block.__(1, [/* :: */[
                          /* One */Block.__(0, ["c"]),
                          /* :: */[
                            /* One */Block.__(0, ["d"]),
                            /* [] */0
                          ]
                        ]]),
                    /* :: */[
                      /* One */Block.__(0, ["e"]),
                      /* [] */0
                    ]
                  ]
                ]]),
            /* [] */0
          ]
        ]));

console.log(flatten2(/* :: */[
          /* One */Block.__(0, ["a"]),
          /* :: */[
            /* Many */Block.__(1, [/* :: */[
                  /* One */Block.__(0, ["b"]),
                  /* :: */[
                    /* Many */Block.__(1, [/* :: */[
                          /* One */Block.__(0, ["c"]),
                          /* :: */[
                            /* One */Block.__(0, ["d"]),
                            /* [] */0
                          ]
                        ]]),
                    /* :: */[
                      /* One */Block.__(0, ["e"]),
                      /* [] */0
                    ]
                  ]
                ]]),
            /* [] */0
          ]
        ]));

exports.flatten  = flatten;
exports.aux      = aux;
exports.flatten2 = flatten2;
/*  Not a pure module */
