// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List     = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function compress(l) {
  var aux = function (_l, _acc) {
    while(true) {
      var acc = _acc;
      var l = _l;
      if (l) {
        var match = l[1];
        if (match) {
          var rest = match[1];
          var b = match[0];
          var a = l[0];
          if (Caml_obj.caml_equal(a, b)) {
            _l = /* :: */[
              b,
              rest
            ];
            continue ;
            
          } else {
            _acc = /* :: */[
              a,
              acc
            ];
            _l = /* :: */[
              b,
              rest
            ];
            continue ;
            
          }
        } else {
          return acc;
        }
      } else {
        return acc;
      }
    };
  };
  return List.rev(aux(l, /* [] */0));
}

console.log(compress(/* :: */[
          "a",
          /* :: */[
            "a",
            /* :: */[
              "a",
              /* :: */[
                "a",
                /* :: */[
                  "b",
                  /* :: */[
                    "c",
                    /* :: */[
                      "c",
                      /* :: */[
                        "a",
                        /* :: */[
                          "a",
                          /* :: */[
                            "d",
                            /* :: */[
                              "e",
                              /* :: */[
                                "e",
                                /* :: */[
                                  "e",
                                  /* :: */[
                                    "e",
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]));

exports.compress = compress;
/*  Not a pure module */
