// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List     = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function pack(l) {
  var aux = function (_l, _acc, _accSub) {
    while(true) {
      var accSub = _accSub;
      var acc = _acc;
      var l = _l;
      if (l) {
        var match = l[1];
        if (match) {
          var rest = match[1];
          var b = match[0];
          if (Caml_obj.caml_equal(l[0], b)) {
            _accSub = /* :: */[
              b,
              accSub
            ];
            _l = /* :: */[
              b,
              rest
            ];
            continue ;
            
          } else {
            _accSub = /* :: */[
              b,
              /* [] */0
            ];
            _acc = /* :: */[
              accSub,
              acc
            ];
            _l = /* :: */[
              b,
              rest
            ];
            continue ;
            
          }
        } else {
          return /* :: */[
                  accSub,
                  acc
                ];
        }
      } else {
        return /* :: */[
                accSub,
                acc
              ];
      }
    };
  };
  return List.rev(l ? aux(l, /* [] */0, /* :: */[
                    l[0],
                    /* [] */0
                  ]) : /* [] */0);
}

function pack2(l) {
  var aux = function (_l, _acc, _accSub) {
    while(true) {
      var accSub = _accSub;
      var acc = _acc;
      var l = _l;
      if (l) {
        var match = l[1];
        var a = l[0];
        if (match) {
          var rest = match[1];
          var b = match[0];
          if (Caml_obj.caml_equal(a, b)) {
            _accSub = /* :: */[
              a,
              accSub
            ];
            _l = /* :: */[
              b,
              rest
            ];
            continue ;
            
          } else {
            _accSub = /* [] */0;
            _acc = /* :: */[
              /* :: */[
                a,
                accSub
              ],
              acc
            ];
            _l = /* :: */[
              b,
              rest
            ];
            continue ;
            
          }
        } else {
          return /* :: */[
                  /* :: */[
                    a,
                    accSub
                  ],
                  acc
                ];
        }
      } else {
        return /* [] */0;
      }
    };
  };
  return List.rev(aux(l, /* [] */0, /* [] */0));
}

console.log(pack(/* :: */[
          "a",
          /* :: */[
            "a",
            /* :: */[
              "a",
              /* :: */[
                "a",
                /* :: */[
                  "b",
                  /* :: */[
                    "c",
                    /* :: */[
                      "c",
                      /* :: */[
                        "a",
                        /* :: */[
                          "a",
                          /* :: */[
                            "d",
                            /* :: */[
                              "e",
                              /* :: */[
                                "e",
                                /* :: */[
                                  "e",
                                  /* :: */[
                                    "e",
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]));

console.log(pack2(/* :: */[
          "a",
          /* :: */[
            "a",
            /* :: */[
              "a",
              /* :: */[
                "a",
                /* :: */[
                  "b",
                  /* :: */[
                    "c",
                    /* :: */[
                      "c",
                      /* :: */[
                        "a",
                        /* :: */[
                          "a",
                          /* :: */[
                            "d",
                            /* :: */[
                              "e",
                              /* :: */[
                                "e",
                                /* :: */[
                                  "e",
                                  /* :: */[
                                    "e",
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]));

exports.pack  = pack;
exports.pack2 = pack2;
/*  Not a pure module */
