// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List  = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");

function decode(l) {
  var elem = function (_e, _acc) {
    while(true) {
      var acc = _acc;
      var e = _e;
      if (e.tag) {
        var match = e[0];
        var c = match[1];
        var cnt = match[0];
        if (cnt > 2) {
          _acc = /* :: */[
            c,
            acc
          ];
          _e = /* Many */Block.__(1, [/* tuple */[
                cnt - 1 | 0,
                c
              ]]);
          continue ;
          
        } else {
          _acc = /* :: */[
            c,
            acc
          ];
          _e = /* One */Block.__(0, [c]);
          continue ;
          
        }
      } else {
        return /* :: */[
                e[0],
                acc
              ];
      }
    };
  };
  var aux = function (_l, _acc) {
    while(true) {
      var acc = _acc;
      var l = _l;
      if (l) {
        _acc = elem(l[0], acc);
        _l = l[1];
        continue ;
        
      } else {
        return acc;
      }
    };
  };
  return List.rev(aux(l, /* [] */0));
}

console.log(decode(/* :: */[
          /* Many */Block.__(1, [/* tuple */[
                4,
                "a"
              ]]),
          /* :: */[
            /* One */Block.__(0, ["b"]),
            /* :: */[
              /* Many */Block.__(1, [/* tuple */[
                    2,
                    "c"
                  ]]),
              /* :: */[
                /* Many */Block.__(1, [/* tuple */[
                      2,
                      "a"
                    ]]),
                /* :: */[
                  /* One */Block.__(0, ["d"]),
                  /* :: */[
                    /* Many */Block.__(1, [/* tuple */[
                          4,
                          "e"
                        ]]),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]));

exports.decode = decode;
/*  Not a pure module */
