// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function duplicate(l) {
  var aux = function (_l, _accum) {
    while(true) {
      var accum = _accum;
      var l = _l;
      if (l) {
        var a = l[0];
        _accum = /* :: */[
          a,
          /* :: */[
            a,
            accum
          ]
        ];
        _l = l[1];
        continue ;
        
      } else {
        return accum;
      }
    };
  };
  return List.rev(aux(l, /* [] */0));
}

console.log(duplicate(/* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "c",
                /* :: */[
                  "d",
                  /* [] */0
                ]
              ]
            ]
          ]
        ]));

exports.duplicate = duplicate;
/*  Not a pure module */
