// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function replicate(l, n) {
  var dup = function (a, _n, _accum) {
    while(true) {
      var accum = _accum;
      var n = _n;
      if (n !== 0) {
        _accum = /* :: */[
          a,
          accum
        ];
        _n = n - 1 | 0;
        continue ;
        
      } else {
        return accum;
      }
    };
  };
  var _l = List.rev(l);
  var _accum = /* [] */0;
  while(true) {
    var accum = _accum;
    var l$1 = _l;
    if (l$1) {
      _accum = dup(l$1[0], n, accum);
      _l = l$1[1];
      continue ;
      
    } else {
      return accum;
    }
  };
}

console.log(replicate(/* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* [] */0
            ]
          ]
        ], 2));

exports.replicate = replicate;
/*  Not a pure module */
