// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function split(l, n) {
  var _l = l;
  var _n = n;
  var _accum = /* [] */0;
  while(true) {
    var accum = _accum;
    var n$1 = _n;
    var l$1 = _l;
    var exit = 0;
    if (n$1 !== 1) {
      exit = 1;
    } else if (l$1) {
      return /* tuple */[
              List.rev(/* :: */[
                    l$1[0],
                    accum
                  ]),
              l$1[1]
            ];
    } else {
      exit = 1;
    }
    if (exit === 1) {
      if (l$1) {
        _accum = /* :: */[
          l$1[0],
          accum
        ];
        _n = n$1 - 1 | 0;
        _l = l$1[1];
        continue ;
        
      } else {
        return /* tuple */[
                List.rev(accum),
                /* [] */0
              ];
      }
    }
    
  };
}

console.log(split(/* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* :: */[
                  "e",
                  /* :: */[
                    "f",
                    /* :: */[
                      "g",
                      /* :: */[
                        "h",
                        /* :: */[
                          "i",
                          /* :: */[
                            "j",
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ], 3));

console.log(split(/* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* [] */0
              ]
            ]
          ]
        ], 5));

exports.split = split;
/*  Not a pure module */
