// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function remove_at(k, l) {
  var split = function (_k, _l, _accum) {
    while(true) {
      var accum = _accum;
      var l = _l;
      var k = _k;
      if (l) {
        var rest = l[1];
        if (k !== 0) {
          _accum = /* :: */[
            l[0],
            accum
          ];
          _l = rest;
          _k = k - 1 | 0;
          continue ;
          
        } else {
          return /* tuple */[
                  accum,
                  rest
                ];
        }
      } else {
        return /* tuple */[
                accum,
                /* [] */0
              ];
      }
    };
  };
  var match = split(k, l, /* [] */0);
  var _l = match[0];
  var _accum = match[1];
  while(true) {
    var accum = _accum;
    var l$1 = _l;
    if (l$1) {
      _accum = /* :: */[
        l$1[0],
        accum
      ];
      _l = l$1[1];
      continue ;
      
    } else {
      return accum;
    }
  };
}

console.log(remove_at(1, /* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* [] */0
              ]
            ]
          ]
        ]));

exports.remove_at = remove_at;
/*  Not a pure module */
