// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function insert_at(v, k, l) {
  var aux = function (_k, _l, _accum) {
    while(true) {
      var accum = _accum;
      var l = _l;
      var k = _k;
      if (k !== 0) {
        if (l) {
          _accum = /* :: */[
            l[0],
            accum
          ];
          _l = l[1];
          _k = k - 1 | 0;
          continue ;
          
        } else {
          return accum;
        }
      } else {
        _accum = /* :: */[
          v,
          accum
        ];
        _k = -1;
        continue ;
        
      }
    };
  };
  return List.rev(aux(k, l, /* [] */0));
}

console.log(insert_at("alfa", 1, /* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* [] */0
              ]
            ]
          ]
        ]));

console.log(insert_at("alfa", 3, /* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* [] */0
              ]
            ]
          ]
        ]));

console.log(insert_at("alfa", 4, /* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* [] */0
              ]
            ]
          ]
        ]));

exports.insert_at = insert_at;
/*  Not a pure module */
