// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function range(a, b) {
  var aux = function (_a, _accum) {
    while(true) {
      var accum = _accum;
      var a = _a;
      if (a === b) {
        return /* :: */[
                a,
                accum
              ];
      } else {
        _accum = /* :: */[
          a,
          accum
        ];
        _a = a + 1 | 0;
        continue ;
        
      }
    };
  };
  if (a <= b) {
    return List.rev(aux(a, /* [] */0));
  } else {
    return aux(a, /* [] */0);
  }
}

console.log(range(4, 9));

console.log(range(9, 4));

exports.range = range;
/*  Not a pure module */
