// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List   = require("bs-platform/lib/js/list.js");
var Random = require("bs-platform/lib/js/random.js");

function pop(k, l) {
  var split = function (_k, _l, _accum) {
    while(true) {
      var accum = _accum;
      var l = _l;
      var k = _k;
      if (l) {
        var rest = l[1];
        var a = l[0];
        if (k !== 0) {
          _accum = /* :: */[
            a,
            accum
          ];
          _l = rest;
          _k = k - 1 | 0;
          continue ;
          
        } else {
          return /* tuple */[
                  /* Some */[a],
                  accum,
                  rest
                ];
        }
      } else {
        return /* tuple */[
                /* None */0,
                accum,
                /* [] */0
              ];
      }
    };
  };
  var into = function (_l, _accum) {
    while(true) {
      var accum = _accum;
      var l = _l;
      if (l) {
        _accum = /* :: */[
          l[0],
          accum
        ];
        _l = l[1];
        continue ;
        
      } else {
        return accum;
      }
    };
  };
  var match = split(k, l, /* [] */0);
  return /* tuple */[
          match[0],
          into(match[1], match[2])
        ];
}

function rand_select(l, n) {
  var _l = l;
  var _n = n;
  var _accum = /* [] */0;
  while(true) {
    var accum = _accum;
    var n$1 = _n;
    var l$1 = _l;
    if (n$1) {
      var c = Random.$$int(List.length(l$1));
      var match = pop(c, l$1);
      var e = match[0];
      if (e) {
        _accum = /* :: */[
          e[0],
          accum
        ];
        _n = n$1 - 1 | 0;
        _l = match[1];
        continue ;
        
      } else {
        return accum;
      }
    } else {
      return accum;
    }
  };
}

console.log(rand_select(/* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* :: */[
                  "e",
                  /* :: */[
                    "f",
                    /* :: */[
                      "g",
                      /* :: */[
                        "h",
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ], 3));

console.log(rand_select(/* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* :: */[
                  "e",
                  /* :: */[
                    "f",
                    /* :: */[
                      "g",
                      /* :: */[
                        "h",
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ], 2));

exports.pop         = pop;
exports.rand_select = rand_select;
/*  Not a pure module */
