// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List                    = require("bs-platform/lib/js/list.js");
var Pervasives              = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function extract(n, l) {
  if (List.length(l) === n) {
    return /* :: */[
            l,
            /* [] */0
          ];
  } else if (n) {
    if (l) {
      var t = l[1];
      var h = l[0];
      return Pervasives.$at(List.map((function (e) {
                        return /* :: */[
                                h,
                                e
                              ];
                      }), extract(n - 1 | 0, t)), extract(n, t));
    } else {
      throw Caml_builtin_exceptions.not_found;
    }
  } else {
    return /* :: */[
            /* [] */0,
            /* [] */0
          ];
  }
}

console.log(extract(2, /* :: */[
          "a",
          /* :: */[
            "b",
            /* :: */[
              "c",
              /* :: */[
                "d",
                /* :: */[
                  "e",
                  /* [] */0
                ]
              ]
            ]
          ]
        ]));

exports.extract = extract;
/*  Not a pure module */
