// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function gcd(_x, _y) {
  while(true) {
    var y = _y;
    var x = _x;
    if (y !== 0) {
      _y = Caml_int32.mod_(x, y);
      _x = y;
      continue ;
      
    } else {
      return x;
    }
  };
}

function coprime(x, y) {
  return +(gcd(x, y) === 1);
}

console.log(coprime(13, 27));

console.log(coprime(20536, 7826));

console.log(coprime(105, 25));

exports.gcd     = gcd;
exports.coprime = coprime;
/*  Not a pure module */
