// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function gcd(_x, _y) {
  while(true) {
    var y = _y;
    var x = _x;
    if (y !== 0) {
      _y = Caml_int32.mod_(x, y);
      _x = y;
      continue ;
      
    } else {
      return x;
    }
  };
}

function phi(x) {
  var _r = x - 1 | 0;
  var _cnt = 0;
  while(true) {
    var cnt = _cnt;
    var r = _r;
    if (r !== 1) {
      if (gcd(x, r) === 1) {
        _cnt = cnt + 1 | 0;
        _r = r - 1 | 0;
        continue ;
        
      } else {
        _r = r - 1 | 0;
        continue ;
        
      }
    } else {
      return cnt + 1 | 0;
    }
  };
}

console.log(phi(10));

console.log(phi(13));

exports.gcd = gcd;
exports.phi = phi;
/*  Not a pure module */
