// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function gray(n) {
  if (n === 1) {
    return /* :: */[
            "0",
            /* :: */[
              "1",
              /* [] */0
            ]
          ];
  } else {
    var base_bits = gray(n - 1 | 0);
    return List.append(List.map((function (pat) {
                      return "0" + pat;
                    }), base_bits), List.rev_map((function (pat) {
                      return "1" + pat;
                    }), base_bits));
  }
}

console.log(gray(1));

console.log(gray(2));

console.log(gray(3));

exports.gray = gray;
/*  Not a pure module */
