// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function is_mirror(_left, _right) {
  while(true) {
    var right = _right;
    var left = _left;
    if (left) {
      if (right) {
        if (is_mirror(left[1], right[2])) {
          _right = right[1];
          _left = left[2];
          continue ;
          
        } else {
          return /* false */0;
        }
      } else {
        return /* false */0;
      }
    } else if (right) {
      return /* false */0;
    } else {
      return /* true */1;
    }
  };
}

function is_symmetric(t) {
  if (t) {
    return is_mirror(t[1], t[2]);
  } else {
    return /* true */1;
  }
}

console.log(is_symmetric(/* Node */[
          /* "x" */120,
          /* Node */[
            /* "x" */120,
            /* Empty */0,
            /* Empty */0
          ],
          /* Node */[
            /* "x" */120,
            /* Empty */0,
            /* Empty */0
          ]
        ]));

console.log(is_symmetric(/* Node */[
          /* "x" */120,
          /* Node */[
            /* "x" */120,
            /* Empty */0,
            /* Empty */0
          ],
          /* Empty */0
        ]));

console.log(is_symmetric(/* Node */[
          /* "x" */120,
          /* Node */[
            /* "x" */120,
            /* Node */[
              /* "x" */120,
              /* Empty */0,
              /* Empty */0
            ],
            /* Empty */0
          ],
          /* Node */[
            /* "x" */120,
            /* Empty */0,
            /* Node */[
              /* "x" */120,
              /* Empty */0,
              /* Empty */0
            ]
          ]
        ]));

console.log(is_symmetric(/* Node */[
          /* "x" */120,
          /* Node */[
            /* "x" */120,
            /* Node */[
              /* "x" */120,
              /* Empty */0,
              /* Empty */0
            ],
            /* Empty */0
          ],
          /* Node */[
            /* "x" */120,
            /* Node */[
              /* "x" */120,
              /* Empty */0,
              /* Empty */0
            ],
            /* Node */[
              /* "x" */120,
              /* Empty */0,
              /* Empty */0
            ]
          ]
        ]));

exports.is_mirror    = is_mirror;
exports.is_symmetric = is_symmetric;
/*  Not a pure module */
