// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List     = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function construct(nums) {
  var insert = function (tree, num) {
    if (tree) {
      var r = tree[2];
      var l = tree[1];
      var v = tree[0];
      if (Caml_obj.caml_lessthan(num, v)) {
        return /* Node */[
                v,
                insert(l, num),
                r
              ];
      } else {
        return /* Node */[
                v,
                l,
                insert(r, num)
              ];
      }
    } else {
      return /* Node */[
              num,
              /* Empty */0,
              /* Empty */0
            ];
    }
  };
  return List.fold_left(insert, /* Empty */0, nums);
}

console.log(construct(/* :: */[
          3,
          /* :: */[
            2,
            /* :: */[
              5,
              /* :: */[
                7,
                /* :: */[
                  1,
                  /* [] */0
                ]
              ]
            ]
          ]
        ]));

console.log(construct(/* :: */[
          5,
          /* :: */[
            3,
            /* :: */[
              18,
              /* :: */[
                1,
                /* :: */[
                  4,
                  /* :: */[
                    12,
                    /* :: */[
                      21,
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]));

exports.construct = construct;
/*  Not a pure module */
