// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function leaves(tree) {
  var traverse = function (_tree, _accum) {
    while(true) {
      var accum = _accum;
      var tree = _tree;
      if (tree) {
        var left = tree[1];
        if (left) {
          _accum = traverse(tree[2], accum);
          _tree = left;
          continue ;
          
        } else if (tree[2]) {
          _accum = traverse(tree[2], accum);
          _tree = left;
          continue ;
          
        } else {
          return /* :: */[
                  tree[0],
                  accum
                ];
        }
      } else {
        return accum;
      }
    };
  };
  return traverse(tree, /* [] */0);
}

console.log(leaves(/* Node */[
          "x",
          /* Node */[
            "x",
            /* Node */[
              "x",
              /* Empty */0,
              /* Empty */0
            ],
            /* Empty */0
          ],
          /* Node */[
            "x",
            /* Empty */0,
            /* Node */[
              "x",
              /* Empty */0,
              /* Empty */0
            ]
          ]
        ]));

exports.leaves = leaves;
/*  Not a pure module */
