// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function internals(tree) {
  var traverse = function (_tree, _accum) {
    while(true) {
      var accum = _accum;
      var tree = _tree;
      if (tree) {
        var left = tree[1];
        var exit = 0;
        if (left) {
          exit = 1;
        } else if (tree[2]) {
          exit = 1;
        } else {
          return accum;
        }
        if (exit === 1) {
          _accum = traverse(tree[2], /* :: */[
                tree[0],
                accum
              ]);
          _tree = left;
          continue ;
          
        }
        
      } else {
        return accum;
      }
    };
  };
  return traverse(tree, /* [] */0);
}

console.log(internals(/* Node */[
          "a",
          /* Node */[
            "b",
            /* Node */[
              "d",
              /* Empty */0,
              /* Empty */0
            ],
            /* Node */[
              "e",
              /* Empty */0,
              /* Empty */0
            ]
          ],
          /* Node */[
            "c",
            /* Empty */0,
            /* Node */[
              "f",
              /* Node */[
                "g",
                /* Empty */0,
                /* Empty */0
              ],
              /* Empty */0
            ]
          ]
        ]));

exports.internals = internals;
/*  Not a pure module */
