// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function at_level(tree, desired_level) {
  var traverse = function (_tree, _level, _accum) {
    while(true) {
      var accum = _accum;
      var level = _level;
      var tree = _tree;
      if (tree) {
        if (level === desired_level) {
          return /* :: */[
                  tree[0],
                  accum
                ];
        } else {
          _accum = traverse(tree[2], level + 1 | 0, accum);
          _level = level + 1 | 0;
          _tree = tree[1];
          continue ;
          
        }
      } else {
        return accum;
      }
    };
  };
  return traverse(tree, 1, /* [] */0);
}

console.log(at_level(/* Node */[
          "a",
          /* Node */[
            "b",
            /* Node */[
              "d",
              /* Empty */0,
              /* Empty */0
            ],
            /* Node */[
              "e",
              /* Empty */0,
              /* Empty */0
            ]
          ],
          /* Node */[
            "c",
            /* Empty */0,
            /* Node */[
              "f",
              /* Node */[
                "g",
                /* Empty */0,
                /* Empty */0
              ],
              /* Empty */0
            ]
          ]
        ], 2));

exports.at_level = at_level;
/*  Not a pure module */
