// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function count_nodes(tree) {
  var children = tree[1];
  if (children) {
    return List.fold_left((function (a, b) {
                  return a + b | 0;
                }), 1, List.map(count_nodes, children));
  } else {
    return 1;
  }
}

console.log(count_nodes(/* T */[
          /* "a" */97,
          /* :: */[
            /* T */[
              /* "f" */102,
              /* [] */0
            ],
            /* [] */0
          ]
        ]));

exports.count_nodes = count_nodes;
/*  Not a pure module */
