// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function ipl(tree) {
  var aux = function (tree, pl) {
    return List.fold_left((function (cnt, t) {
                  return cnt + aux(t, pl + 1 | 0) | 0;
                }), 0, tree[1]) + pl | 0;
  };
  return aux(tree, 0);
}

console.log(ipl(/* T */[
          /* "a" */97,
          /* :: */[
            /* T */[
              /* "f" */102,
              /* :: */[
                /* T */[
                  /* "g" */103,
                  /* [] */0
                ],
                /* [] */0
              ]
            ],
            /* :: */[
              /* T */[
                /* "c" */99,
                /* [] */0
              ],
              /* :: */[
                /* T */[
                  /* "b" */98,
                  /* :: */[
                    /* T */[
                      /* "d" */100,
                      /* [] */0
                    ],
                    /* :: */[
                      /* T */[
                        /* "e" */101,
                        /* [] */0
                      ],
                      /* [] */0
                    ]
                  ]
                ],
                /* [] */0
              ]
            ]
          ]
        ]));

exports.ipl = ipl;
/*  Not a pure module */
