// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function bottom_up(tree) {
  var aux = function (tree, acc) {
    return /* :: */[
            tree[0],
            List.fold_left((function (acc, node) {
                    return aux(node, acc);
                  }), acc, tree[1])
          ];
  };
  return List.rev(aux(tree, /* [] */0));
}

console.log(bottom_up(/* T */[
          /* "a" */97,
          /* :: */[
            /* T */[
              /* "f" */102,
              /* :: */[
                /* T */[
                  /* "g" */103,
                  /* [] */0
                ],
                /* [] */0
              ]
            ],
            /* :: */[
              /* T */[
                /* "c" */99,
                /* [] */0
              ],
              /* :: */[
                /* T */[
                  /* "b" */98,
                  /* :: */[
                    /* T */[
                      /* "d" */100,
                      /* [] */0
                    ],
                    /* :: */[
                      /* T */[
                        /* "e" */101,
                        /* [] */0
                      ],
                      /* [] */0
                    ]
                  ]
                ],
                /* [] */0
              ]
            ]
          ]
        ]));

exports.bottom_up = bottom_up;
/*  Not a pure module */
