// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Char = require("bs-platform/lib/js/char.js");
var List = require("bs-platform/lib/js/list.js");

function lispy(tree) {
  var children = tree[1];
  var c = tree[0];
  if (children) {
    return "(" + Char.escaped(c) + List.fold_left((function (s, sub_tree) {
                  return s + " " + lispy(sub_tree);
                }), "", children) + ")";
  } else {
    return Char.escaped(c);
  }
}

console.log(lispy(/* T */[
          /* "a" */97,
          /* [] */0
        ]));

console.log(lispy(/* T */[
          /* "a" */97,
          /* :: */[
            /* T */[
              /* "b" */98,
              /* [] */0
            ],
            /* [] */0
          ]
        ]));

console.log(lispy(/* T */[
          /* "a" */97,
          /* :: */[
            /* T */[
              /* "f" */102,
              /* :: */[
                /* T */[
                  /* "g" */103,
                  /* [] */0
                ],
                /* [] */0
              ]
            ],
            /* :: */[
              /* T */[
                /* "c" */99,
                /* [] */0
              ],
              /* :: */[
                /* T */[
                  /* "b" */98,
                  /* :: */[
                    /* T */[
                      /* "d" */100,
                      /* [] */0
                    ],
                    /* :: */[
                      /* T */[
                        /* "e" */101,
                        /* [] */0
                      ],
                      /* [] */0
                    ]
                  ]
                ],
                /* [] */0
              ]
            ]
          ]
        ]));

exports.lispy = lispy;
/*  Not a pure module */
